### ISSUE TITLE
Treating multipage Captive Portal

### ISSUE THREAD

**Issue by ambarusa** [CDFER/Captive-Portal-ESP32#6]
Hi. I am looking for a solution to have a multipage captive portal, basically the same page as it could be accessed when connected to a network. Do you have any ideas for that?

**Comment by CDFER** [comment]
have a look at my open source air quality firmware https://github.com/CDFER/Kea-CO2/pull/6

**Comment by CDFER** [comment]
I use the littleFS file system and the same ESPAsyncWebServer used in this example https://github.com/me-no-dev/ESPAsyncWebServer/tree/master#serving-static-files
